CREATE TABLE users (id SERIAL PRIMARY KEY,
                                      fname VARCHAR(255),
                                            lname VARCHAR(255),
                                                  email VARCHAR(255) NOT NULL,
                                                                     password VARCHAR(255) NOT NULL,
                                                                                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                                                                                        deleted_at TIMESTAMP,
                                                                                                                                   updated_at TIMESTAMP);


INSERT INTO users (fname, lname, email, password, created_at, deleted_at, updated_at)
VALUES ('John',
        'Doe',
        'johndoe@example.com',
        'Password@123',
        '2023-01-01 10:00:00',
        NULL,
        '2023-01-01 10:00:00'), ('Jane',
                                 'Smith',
                                 'janesmith@example.com',
                                 'Password@123',
                                 '2023-01-02 11:00:00',
                                 NULL,
                                 '2023-01-02 11:00:00'), ('Alice',
                                                          'Johnson',
                                                          'alicejohnson@example.com',
                                                          'Password@123',
                                                          '2023-01-03 12:00:00',
                                                          NULL,
                                                          '2023-01-03 12:00:00'), ('Bob',
                                                                                   'Brown',
                                                                                   'bobbrown@example.com',
                                                                                   'Password@123',
                                                                                   '2023-01-04 13:00:00',
                                                                                   NULL,
                                                                                   '2023-01-04 13:00:00'), ('Charlie',
                                                                                                            'Davis',
                                                                                                            'charliedavis@example.com',
                                                                                                            'Password@123',
                                                                                                            '2023-01-05 14:00:00',
                                                                                                            NULL,
                                                                                                            '2023-01-05 14:00:00');


create Table product (id serial PRIMARY KEY, product_name Text, price TEXT, Image TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP, updated_at TIMESTAMP)
INSERT INTO product (product_name, price, created_at, deleted_at, updated_at)
VALUES ('Product 1',
        '10.00',
        '2023-01-01 10:00:00',
        NULL,
        '2023-01-01 10:00:00'), ('Product 2',
                                 '20.00',
                                 '2023-01-02 11:00:00',
                                 NULL,
                                 '2023-01-02 11:00:00'), ('Product 3',
                                                          '30.00',
                                                          '2023-01-03 12:00:00',
                                                          NULL,
                                                          '2023-01-03 12:00:00'), ('Product 4',
                                                                                   '40.00',
                                                                                   '2023-01-04 13:00:00',
                                                                                   NULL,
                                                                                   '2023-01-04 13:00:00'), ('Product 5',
                                                                                                            '50.00',
                                                                                                            '2023-01-05 14:00:00',
                                                                                                            NULL,
                                                                                                            '2023-01-05 14:00:00');